<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VoucherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vouchers = [
            [
                'voucher_code' => 'FREESHIP',
                'discount_type' => 'fixed',
                'quantity' => 100,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 30000.00,
                'sale_price' => 30000.00,
                'min_order_value' => 200000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'status' => 1,
                'description' => 'Miễn phí vận chuyển cho đơn hàng từ 200.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'DISCOUNT10',
                'discount_type' => 'percent',
                'quantity' => 200,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 10,
                'sale_price' => 0.00,
                'min_order_value' => 300000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(3),
                'status' => 1,
                'description' => 'Giảm 10% trên tổng tiền thanh toán cho đơn hàng từ 300.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'DISCOUNT15',
                'discount_type' => 'percent',
                'quantity' => 150,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 15,
                'sale_price' => 0.00,
                'min_order_value' => 500000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(4),
                'status' => 1,
                'description' => 'Giảm 15% trên tổng tiền thanh toán cho đơn hàng từ 500.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'DISCOUNT20',
                'discount_type' => 'percent',
                'quantity' => 100,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 20,
                'sale_price' => 0.00,
                'min_order_value' => 800000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(5),
                'status' => 1,
                'description' => 'Giảm 20% trên tổng tiền thanh toán cho đơn hàng từ 800.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'GIAM50K',
                'discount_type' => 'fixed',
                'quantity' => 300,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 50000.00,
                'sale_price' => 50000.00,
                'min_order_value' => 300000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(2),
                'status' => 1,
                'description' => 'Giảm 50.000đ cho đơn hàng từ 300.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'GIAM100K',
                'discount_type' => 'fixed',
                'quantity' => 200,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 100000.00,
                'sale_price' => 100000.00,
                'min_order_value' => 500000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(3),
                'status' => 1,
                'description' => 'Giảm 100.000đ cho đơn hàng từ 500.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'GIAM200K',
                'discount_type' => 'fixed',
                'quantity' => 100,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 200000.00,
                'sale_price' => 200000.00,
                'min_order_value' => 1000000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'status' => 1,
                'description' => 'Giảm 200.000đ cho đơn hàng từ 1.000.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'NEWUSER',
                'discount_type' => 'fixed',
                'quantity' => 500,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 100000.00,
                'sale_price' => 100000.00,
                'min_order_value' => 200000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(12),
                'status' => 1,
                'description' => 'Voucher dành cho khách hàng mới - Giảm 100.000đ cho đơn hàng từ 200.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'VIP30',
                'discount_type' => 'percent',
                'quantity' => 50,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 30,
                'sale_price' => 0.00,
                'min_order_value' => 1000000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(12),
                'status' => 1,
                'description' => 'Voucher VIP - Giảm 30% trên tổng tiền cho đơn hàng từ 1.000.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'voucher_code' => 'SALE25',
                'discount_type' => 'percent',
                'quantity' => 80,
                'total_used' => 0,
                'user_limit' => 1,
                'discount_value' => 25,
                'sale_price' => 0.00,
                'min_order_value' => 1000000.00,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'status' => 1,
                'description' => 'Giảm 25% trên tổng tiền thanh toán cho đơn hàng từ 1.000.000đ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($vouchers as $voucher) {
            DB::table('vouchers')->insert($voucher);
        }
    }
}


